# Generated by Django 5.2.5 on 2025-09-01 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nombre', models.CharField(max_length=100)),
                ('plan_id_ref', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('moneda', models.CharField(default='COP', max_length=10)),
                ('proveedor', models.CharField(choices=[('mercadopago', 'MercadoPago')], default='mercadopago', max_length=20)),
                ('proveedor_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('proveedor_preference_id', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
