# Generated by Django 5.2.5 on 2025-09-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(db_column='id_perfil', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('es_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
    ]
