# Generated by Django 5.2.5 on 2025-09-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
