# Generated by Django 5.2.5 on 2025-09-02 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='movies/%Y/%m/%d/')),
                ('remote_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('calidad', models.CharField(default='1080p', max_length=20)),
                ('mime_type', models.CharField(default='video/mp4', max_length=50)),
                ('es_trailer', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(db_column='id_pelicula', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='content.pelicula')),
            ],
            options={
                'db_table': 'media_assets',
            },
        ),
    ]
