# Generated by Django 5.2.5 on 2025-09-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('id_perfil', models.IntegerField(db_column='id_perfil')),
                ('id_pelicula', models.IntegerField(db_column='id_pelicula')),
                ('fecha_vista', models.DateTimeField(auto_now_add=True, db_column='fecha_vista')),
                ('progreso_segundos', models.IntegerField(db_column='progreso_segundos', default=0)),
                ('terminado', models.BooleanField(db_column='terminado', default=False)),
            ],
            options={
                'db_table': 'historial',
                'ordering': ['-fecha_vista'],
                'managed': False,
            },
        ),
    ]
