# Generated by Django 5.2.5 on 2025-09-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'managed': True},
        ),
    ]
