# Generated by Django 5.2.5 on 2025-09-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAssetReadOnly',
            fields=[
            ],
            options={
                'verbose_name': 'Revisión de media',
                'verbose_name_plural': 'Revisión de media',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uploader.mediaasset',),
        ),
    ]
